# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f94feb263c3b6ede43670ad9b3d296f358d6db89ae6136e46789fdefe7cdcc17a95b3936f496f08f78d5ffc82e1cb7e51abc56d4889fe4ae587f512036ea996

test:
  secret_key_base: 9f863b8ee01d07e48939a334befeca98e2f0fcb39ed27c260977ff3f7283b0c9f9f06fb6e135f65f317e86c3e30ca243dba0addd2684f7a55b582cb2e165743f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
